services:
  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: backend
    working_dir: /app/backend
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - PORT=5000
      - PYTHONPATH=/app
    deploy:
      resources:
        limits:
          memory: 1.5G
        reservations:
          memory: 1G
    ports:
      - "5000:5000" # Flask 
      - "5005:5005" #Rasa
    volumes:
      - ../backend:/app/backend
    depends_on:
      - db
    command: ["/bin/sh", "/app/backend/start.sh"]

  frontend:
    image: node:18
    container_name: frontend
    working_dir: /frontend
    volumes:
      - ../frontend:/frontend
      - /frontend/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm start"

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: retail
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: